version: "3.9"
services:
  api-gateway:
    build: ../../api-gateway
    ports:
      - "8080:8080"

  auth-service:
    build: ../../services/auth-service
    ports:
      - "9001:9001"

  movie-service:
    build: ../../services/movie-service
    ports:
      - "9002:9002"

  user-service:
    build: ../../services/user-service
    ports:
      - "9003:9003"
